.TH CREEPY 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
creepy \- Herramienta de recolección de información de geolocalización
.SH SYNOPSIS
.B creepy
.RI [ opciones ] " <nombre_usuario>"
.SH DESCRIPCIÓN
Creepy es una herramienta que recolecta información de geolocalización de usuarios en redes sociales.

.SH OPCIONES
.TP
.BI \-o ", \--output" " <archivo>"
Especifica el archivo de salida donde se guardarán los resultados en formato JSON. Por defecto, el archivo de salida es \fBresultado_creepy.json\fR.

.SH EJEMPLOS
.B
creepy johndoe
.br
.B
creepy \-o resultados.json johndoe

.SH AUTOR
Desarrollado por Creepy Project.
