.TH EYEWITNESS 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
eyewitness \- Herramienta de captura de pantalla de sitios web
.SH SYNOPSIS
.B eyewitness
.RI [ opciones ] " <URL>"
.SH DESCRIPCIÓN
EyeWitness es una herramienta que captura pantallas de sitios web.

.SH OPCIONES
.TP
.BI \-f ", \--file" " <URL>"
Especifica la URL del sitio web para capturar. Los resultados se guardarán en la carpeta \fBresultados_eyewitness\fR.

.SH EJEMPLOS
.B
eyewitness https://example.com
.br
.B
eyewitness \-f https://example.com

.SH AUTOR
Desarrollado por EyeWitness Project.
