.TH MAIGRET 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
maigret \- Herramienta para buscar perfiles en línea por nombre de usuario
.SH SYNOPSIS
.B maigret
.RI [ opciones ] " <nombre_usuario>"
.SH DESCRIPCIÓN
Maigret es una herramienta que busca perfiles en línea por nombre de usuario.

.SH OPCIONES
.TP
.BI \-o ", \--output" " <directorio>"
Especifica el directorio de salida donde se guardarán los resultados. Por defecto, el directorio de salida es \fBresultado_maigret\fR.

.SH EJEMPLOS
.B
maigret johndoe
.br
.B
maigret \-o resultados johndoe

.SH AUTOR
Desarrollado por Maigret Project.
