.TH PHOTON 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
photon \- Herramienta de recolección de información de sitios web
.SH SYNOPSIS
.B photon
.RI [ opciones ] " <URL>"
.SH DESCRIPCIÓN
Photon es una herramienta avanzada de recolección de información de sitios web.

.SH OPCIONES
.TP
.BI \-o ", \--output" " <directorio>"
Especifica el directorio de salida donde se guardarán los resultados. Por defecto, el directorio de salida es \fBresultado_photon\fR.

.SH EJEMPLOS
.B
photon https://example.com
.br
.B
photon \-o resultados https://example.com

.SH AUTOR
Desarrollado por Photon Project.
