.TH SHERLOCK 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
sherlock \- Herramienta para buscar perfiles de redes sociales por nombre de usuario
.SH SYNOPSIS
.B sherlock
.RI [ opciones ] " <nombre_usuario>"
.SH DESCRIPCIÓN
Sherlock es una herramienta que busca perfiles de redes sociales por nombre de usuario.

.SH OPCIONES
.TP
.BI \-o ", \--output" " <archivo>"
Especifica el archivo de salida donde se guardarán los resultados. Por defecto, el archivo de salida es \fBresultado_sherlock.txt\fR.

.SH EJEMPLOS
.B
sherlock johndoe
.br
.B
sherlock \-o resultados.txt johndoe

.SH AUTOR
Desarrollado por Sherlock Project.
