.TH TWINT 1 "July 2024" "Version 1.0" "User Commands"
.SH NAME
twint \- Herramienta de recolección de información de Twitter
.SH SYNOPSIS
.B twint
.RI [ opciones ] " <nombre_usuario>"
.SH DESCRIPCIÓN
Twint es una herramienta avanzada de recolección de información de Twitter.

.SH OPCIONES
.TP
.BI \-o ", \--output" " <archivo>"
Especifica el archivo de salida donde se guardarán los resultados en formato CSV. Por defecto, el archivo de salida es \fBresultado_twint.csv\fR.

.SH EJEMPLOS
.B
twint johndoe
.br
.B
twint \-o resultados.csv johndoe

.SH AUTOR
Desarrollado por Twint Project.
